src/logtool.ui/Models/QueryViewModel.cs
namespace logtool.ui.Models;

public class QueryViewModel
{
    public int Page { get; set; }

    public IEnumerable<string[]> Rows { get; set; }
}

src/logtool.ui/Controllers/ApiController.cs
using System.Text.Json;
using System.Text.RegularExpressions;
using logtool.ui.Infrastructure;
using logtool.ui.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.Sqlite;
using static logtool.LogEntryDataFunctions;
using static logtool.ui.Functions.Functions;

namespace logtool.ui.Controllers
{
    [ApiController]
    [Route("api")]
    public class ApiController : Controller
    {
        private const int ReconnectionInterval = 3000;

        private static readonly JsonSerializerOptions _jsonOptions = new() {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        };

        private readonly ILogger<ApiController> _logger;
        private readonly IJobQueue _jobQueue;
        private readonly IAppClient _appClient;

        public ApiController(
            ILogger<ApiController> logger,
            IJobQueue jobQueue,
            IAppClient appClient)
        {
            _logger = logger;
            _jobQueue = jobQueue;
            _appClient = appClient;
        }

        [HttpPost]
        [Route("newclientid")]
        public Guid NewClientID()
        {
            var id = Guid.NewGuid();

            Directory.CreateDirectory(_appClient.GetDataDirectoryPath(id));

            return id;
        }

        [HttpPost]
        [Route("getfiles")]
        public string[] GetFiles(GetFilesRequest request) =>
            Directory.GetFiles(request.Folder, "*.log");

        [HttpPost]
        [Route("selectfiles")]
        public SelectFilesResponse SelectFiles(SelectFilesRequest request)
        {
            var (valid, logColumns, error) = ValidateAndReturnColumns(request.Files);

            if (!valid)
            {
                return SelectFilesResponse.ValidationError(request.Files, error);
            }

            var (databaseColumns, errors) = GetDatabaseColumns(logColumns, DefaultIISW3CLogMappings);

            var connectionString = _appClient.GetConnectionString(request.ClientID, SqliteOpenMode.ReadWriteCreate);

            using var conn = new SqliteConnection(connectionString);

            conn.Open();

            ResetDatabase(conn);

            CreateDatabaseTable(conn, databaseColumns);

            foreach (var file in request.Files)
            {
                _jobQueue.Enqueue(new LogImportJob(request.ClientID, _appClient, databaseColumns, file));
            }

            _jobQueue.AddingCompleted();

            return SelectFilesResponse.Success(request.Files, databaseColumns, errors);
        }

        [HttpGet]
        [Route("rowcount")]
        public RowCountResponse RowCount(RowCountRequest request)
        {
            using var conn = new SqliteConnection(_appClient.GetConnectionString(request.ClientID));

            conn.Open();

            var command = conn.CreateCommand();

            command.CommandText = "SELECT COUNT(*) FROM entries";

            LogQueryInformation(command);

            return new RowCountResponse {
                TotalRows = Convert.ToInt32(command.ExecuteScalar())
            };
        }

        [HttpPost]
        [Route("resultcount")]
        public ResultCountResponse ResultCount(ResultCountRequest request)
        {
            var (_, where, _, limit) = ParseSqlQuery(request.Query);

            if (limit is not null)
            {
                // If the user has specified a LIMIT manually, just return that as the number of results
                var limitMatch = Regex.Match(limit, @"LIMIT\s+(?<skip>[^\s]+,\s+)?(?<perpage>[^\s]+)", RegexOptions.IgnoreCase);

                var limitCount = int.TryParse(limitMatch.Groups["perpage"].Value, out var n) ? n : 10;

                return new ResultCountResponse {
                    TotalResults = limitCount,
                    TotalPages = GetPageCount(limitCount)
                };
            }

            using var conn = new SqliteConnection(_appClient.GetConnectionString(request.ClientID));

            conn.Open();

            var command = conn.CreateCommand();

            command.CommandText = $"SELECT COUNT(*) FROM entries {where ?? string.Empty} {limit ?? string.Empty}";

            LogQueryInformation(command);

            var count = Convert.ToInt32(command.ExecuteScalar());

            return new ResultCountResponse {
                TotalResults = count,
                TotalPages = GetPageCount(count)
            };
        }

        [HttpPost]
        [Route("export")]
        public bool Export(ExportRequest request)
        {
            var job = new CsvExportJob(request.ClientID, _appClient, request.Query, _appClient.GetCsvExportTempPath(request.ClientID));

            _jobQueue.Enqueue(job);

            _jobQueue.AddingCompleted();

            return true;
        }

        [HttpGet]
        [Route("subscribe/{clientID}")]
        public async Task Subscribe(Guid clientID, CancellationToken cancellationToken)
        {
            Response.Headers.Add("Content-Type", "text/event-stream");
            Response.Headers.Add("Cache-Control", "no-cache");
            Response.Headers.Add("Connection", "keep-alive");

            async void OnFileProcessingJobCompleted(object _, FileProcessingJobCompletedEventArgs eventArgs)
            {
                if (eventArgs.Job.ClientID != clientID)
                {
                    return;
                }

                try
                {
                    if (eventArgs.Job is LogImportJob job && eventArgs.QueueCompleted)
                    {
                        // Last job was a log import, and all log imports are complete, so create the DB indexes
                        var connectionString = _appClient.GetConnectionString(clientID, SqliteOpenMode.ReadWriteCreate);

                        using var conn = new SqliteConnection(connectionString);

                        conn.Open();

                        CreateDatabaseIndexes(conn, job.DatabaseColumns);
                    }

                    object messageData = eventArgs.Job switch {
                        LogImportJob logImportJob => new { type = "logimport", file = Path.GetFileName(logImportJob.File), logImportJob.EntryCount, eventArgs.QueueCompleted, eventArgs.Message },
                        CsvExportJob csvExportJob => new { type = "csvexport", eventArgs.QueueCompleted, eventArgs.Message },
                        _ => throw new NotImplementedException($"Unknown job type: {eventArgs.Job.GetType().Name}")
                    };

                    var json = JsonSerializer.Serialize(messageData, _jsonOptions);

                    await Response.WriteAsync($"retry: {ReconnectionInterval}\r", cancellationToken);
                    await Response.WriteAsync($"data: {json}\r\r", cancellationToken);

                    await Response.Body.FlushAsync(cancellationToken);
                }
                catch (Exception ex)
                {
                    _logger.LogError("Failed to send notification: {Message}", ex.Message);
                }
            }

            _jobQueue.OnFileProcessingJobCompleted += OnFileProcessingJobCompleted;

            try
            {
                while (!cancellationToken.IsCancellationRequested)
                {
                    await Task.Delay(1000, cancellationToken);
                }
            }
            catch (TaskCanceledException)
            {
                _logger.LogDebug("Task cancelled in Subscribe endpoint: user disconnected");
            }
            finally
            {
                _jobQueue.OnFileProcessingJobCompleted -= OnFileProcessingJobCompleted;
            }
        }

        private void LogQueryInformation(SqliteCommand command)
        {
            _logger.LogInformation("Request: {Url}", Request.Path);
            _logger.LogInformation("Command: {CommandText}", command.CommandText);
        }
    }
}

src/logtool.ui/Controllers/HomeController.cs
using System.Text.Json;
using logtool.ui.Infrastructure;
using logtool.ui.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.Sqlite;
using static logtool.LogEntryDataFunctions;
using static logtool.ui.Constants;
using static logtool.ui.Functions.Functions;

namespace logtool.ui.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IAppClient _appClient;

    public HomeController(
        ILogger<HomeController> logger,
        IAppClient appClient)
    {
        _logger = logger;
        _appClient = appClient;
    }

    public IActionResult Index()
    {
        var model = new IndexViewModel();

        return View(model);
    }

    public IActionResult Query(Guid clientID, string query, int page = 1)
    {
        var (select, where, orderby, limit) = ParseSqlQuery(query);

        IEnumerable<string[]> GetResults()
        {
            using var conn = new SqliteConnection(_appClient.GetConnectionString(clientID));

            conn.Open();

            var command = conn.CreateCommand();

            command.CommandText = $"{select} {where} {orderby ?? "ORDER BY date"} {limit ?? $"LIMIT {MaxResultsPerPage * (page - 1)}, {MaxResultsPerPage}"}";

            LogQueryInformation(command);

            using var reader = command.ExecuteReader();

            yield return Enumerable.Range(0, reader.FieldCount).Select(i => reader.GetName(i)).ToArray();

            while (reader.Read())
            {
                yield return Enumerable.Range(0, reader.FieldCount)
                    .Select(i => reader.GetName(i) == "date" ? reader.GetDateTime(i).ToLocalTime().ToString("dd/MM/yyyy HH:mm:ss") : reader.GetString(i))
                    .ToArray();
            }
        }

        var model = new QueryViewModel {
            Page = page,
            Rows = GetResults()
        };

        return View(model);
    }

    public IActionResult DownloadExport(Guid id) =>
        File(_appClient.GetCsvExportDownloadUrl(id), "text/csv", fileDownloadName: $"logtool-export-{DateTime.Now:yyyy-MM-dd-HH-mm-ss}.csv");

    private void LogQueryInformation(SqliteCommand command)
    {
        _logger.LogInformation("Request: {Url}", Request.Path);
        _logger.LogInformation("Command: {CommandText}", command.CommandText);
    }
}

src/logtool.ui/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<form id="getfiles" asp-action="GetFiles" asp-controller="Api">
    <div class="row mb-2">
        <div class="col-md-6">
            <input type="text" id="folder" name="folder" class="form-control" placeholder="Folder" aria-label="Folder" value="" />
        </div>
        <div class="col-md-1">
            <button type="submit" class="btn btn-primary">Load File List</button>
        </div>
    </div>
</form>

<form id="selectfiles" asp-action="SelectFiles" asp-controller="Api">
    <div class="row mb-2">
        <div class="col-md-6">
            <select multiple id="files" name="files" class="form-control"></select>
        </div>
        <div class="col-md-1">
            <button type="submit" class="btn btn-primary">Select Files</button>
        </div>
        <div class="col-md-5">
            <div id="dataloading" class="loading loading-hidden">Working... <span id="dataloading-status"></span>@* [<span id="dataloading-current">-1</span> of <span id="dataloading-total">-1</span> files]*@</div>
        </div>
    </div>
</form>

<p><code id="columns">No data loaded</code></p>

<form id="runquery" asp-action="Query" asp-controller="Home" method="post" target="results">
    <div class="row mb-2">
        <div class="col-md-6">
            <textarea name="query" id="query" class="form-control" placeholder="Query" aria-label="Query"></textarea>
            <input type="hidden" id="page" name="page" value="1" />
            <input type="hidden" id="clientid" name="clientid" value="1" />
        </div>
        <div class="col-md-1">
            <button type="submit" id="querysubmit" class="btn btn-primary">Query</button>
        </div>
        <div class="col-md-1">
            <div id="queryloading" class="loading loading-hidden"></div>
        </div>
    </div>
</form>

<nav aria-label="Page navigation">
    <ul class="pagination" id="pagination"></ul>
</nav>

<p><a id="export" href="#">Export CSV</a></p>

<iframe id="results" name="results"></iframe>

src/logtool.ui/Views/Home/Query.cshtml
@using Microsoft.AspNetCore.Html
@model QueryViewModel

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LogTool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <table id="table-results" class="table table-striped table-hover table-sm table-results">
        @{
            using (var enumerator = Model.Rows.GetEnumerator())
            {
                var firstRow = true;
                var lastRow = !enumerator.MoveNext();

                while (!lastRow)
                {
                    var row = enumerator.Current;

                    if (firstRow)
                    {
                        @(new HtmlString("<thead><tr><th>" + string.Join("</th><th>", row) + "</th></tr></thead><tbody>"))

                        firstRow = false;
                    }
                    else
                    {
                        @(new HtmlString("<tr><td>" + string.Join("</td><td>", row) + "</td></tr>"))
                    }

                    lastRow = !enumerator.MoveNext();

                    if (lastRow)
                    {
                        @(new HtmlString("</tbody>"))
                    }
                }
            }
        }
    </table>
    <script>
        document.getElementById('table-results').style.display = 'table';
    </script>
</body>
</html>